# Generated by Django 3.2.9 on 2021-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrodigital', '0002_encuesta_dimension1'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('pesoc1', models.FloatField(verbose_name='Peso C1')),
                ('pesoc2', models.FloatField(verbose_name='Peso C2')),
                ('pesoc3', models.FloatField(verbose_name='Peso C3')),
                ('pesoc4', models.FloatField(verbose_name='Peso C4')),
                ('pesoc5', models.FloatField(verbose_name='Peso C5')),
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='resultadodimension1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio1', models.FloatField(verbose_name='Criterio 1')),
                ('criterio2', models.FloatField(verbose_name='Criterio 1')),
                ('criterio3', models.FloatField(verbose_name='Criterio 1')),
                ('criterio4', models.FloatField(verbose_name='Criterio 1')),
                ('criterio5', models.FloatField(verbose_name='Criterio 1')),
            ],
        ),
    ]
