# Generated by Django 3.2.9 on 2021-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrodigital', '0003_modelo_resultadodimension1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='dimension1',
            field=models.CharField(choices=[('1', 'muy malo'), ('2', 'malo'), ('3', 'intermedio')], max_length=1, verbose_name=''),
        ),
    ]
