# Generated by Django 3.2.9 on 2021-11-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrodigital', '0004_alter_encuesta_dimension1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='dimension1',
            field=models.CharField(choices=[('1', 'Las desconozco'), ('3', 'intermedio'), ('5', 'las conozco muy bien')], max_length=1, verbose_name='¿Cuál es el grado de conocimiento de las tecnologías digitales aplicadas a su empresa?'),
        ),
    ]
