# Generated by Django 3.2.9 on 2021-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agrodigital', '0005_alter_encuesta_dimension1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='dimension1',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p1_dim1',
            field=models.CharField(choices=[('1', '1-. Las desconozco'), ('2', '2-. algo de conocimiento'), ('3', '3 -.intermedio'), ('4', '4-.'), ('5', '5-. las conozco muy bien')], default=0.00040484008816517477, max_length=1, verbose_name=' 1-. ¿Cuál es el grado de conocimiento de las tecnologías digitales aplicadas a su empresa?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p1_dim2',
            field=models.CharField(choices=[('1', '1-. Mala disposición'), ('2', '2-. '), ('3', '3 -.intermedio'), ('4', '4-.'), ('5', '5-. muy dispuesta')], default=1, max_length=1, verbose_name=' 1-. ¿Qué tan dispuesta está la empresa a hacer cambio para la transformación digital?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p1_dim3',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 1-. ¿ En que grado hacen una recolaccion de datos sobre sus actividades ? '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p1_dim4',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=1, max_length=1, verbose_name=' 1-. En cuanto a los procesos de su empresa:  Las labores manuales ahora se ejecutan con dispositivos tecnológicos '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p1_dim5',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name='1-. En cuanto a su empresa y la relación con sus empleados, en que grado considera las habilidades tecnológicas ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p2_dim1',
            field=models.CharField(choices=[('1', '1-. poco factible'), ('2', '2-.'), ('3', '3-.'), ('4', '4-.'), ('5', '5-. muy factible')], default=0.00040484008816517477, max_length=1, verbose_name=' 2-. Considerando las necesidades y objetivos en su empresa, ¿Qué tan factible sería invertir en tecnologías digitales?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p2_dim2',
            field=models.CharField(choices=[('1', '1-. poco o nada '), ('2', '2-. '), ('3', '3 -.intermedio'), ('4', '4-.'), ('5', '5-. acceso a créditos')], default=0.00040484008816517477, max_length=1, verbose_name=' 2-. ¿Qué nivel de acceso tiene la empresa a la banca formal?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p2_dim3',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 2-. ¿ En que grado se analizan los datos para mejorar en el mercado ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p2_dim4',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 2-. En cuanto a los procesos de su empresa:  Usan programas de gestión de recursos (ERP, CRM, SAP, otros) ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p2_dim5',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=1, max_length=1, verbose_name='2-. En cuanto a su empresa y la relación con sus empleados, cuenta con personal calificado en tecnología que cambian la manera de funcionar ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p3_dim1',
            field=models.CharField(choices=[('1', '1-. poco o nada'), ('2', '2-. se implementará en algun momento'), ('3', '3-.'), ('4', '4-. usualmente las utilizamos '), ('5', '5-. siempre los utilizamos')], default=0.00040484008816517477, max_length=1, verbose_name=' 3-. ¿Evalúan el uso de tecnologías para la realización de procedimientos cotidianos?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p3_dim2',
            field=models.CharField(choices=[('1', '1-. Mala disposición'), ('2', '2-. '), ('3', '3 -.intermedio'), ('4', '4-.'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 3-. ¿En que grado la empresa ha aplicado a proyectos de apoyo gubernamental?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p3_dim3',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 3-. ¿ Consultan datos externos para posicionarse en el mercado ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p3_dim4',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 3-. En cuanto a los procesos de su empresa: Evalúan el uso de tecnologías para uso de agroquímicos, riego, monitoreo, empaquetado, producción, otros procesos ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p3_dim5',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name='3-. En cuanto a su empresa y la relación con sus empleados, cuenta con personal calificado en tecnología que cambian la manera de funcionar ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p4_dim2',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 4-. En que grado modifica o adapta su modelo de negocios a las nuevas tecnologías'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p4_dim3',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 4-. ¿Evalúan la utilización de datos para mejorar sus procesos empresariales ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p4_dim4',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 4-. En cuanto a los procesos de su empresa: Hay monitoreo en tiempo real del estado de los procesos ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p4_dim5',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name='4-. En cuanto a su empresa y la relación con sus empleados, cuenta con personal calificado en tecnología que cambian la manera de funcionar ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p5_dim2',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 5-. En que grado ha incorporado programas o aplicaciones '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p5_dim5',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name='5-. En cuanto a su empresa y la relación con sus empleados, Cuenta con personal calificado para resolver problemas digitales ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p6_dim2',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.medianamente'), ('4', '4-.casi siempre'), ('5', '5-. siempre')], default=0.00040484008816517477, max_length=1, verbose_name=' 6-. ¿ En que grado ha incorporado programas o aplicaciones?  '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='p6_dim5',
            field=models.CharField(choices=[('1', '1-. muy poco o nada'), ('2', '2-. '), ('3', '3 -.intermedio'), ('4', '4-.alto'), ('5', '5-. excelente')], default=0.00040484008816517477, max_length=1, verbose_name='6-. En cuanto a su empresa y la relación con sus empleados, Cuál es el grado de manejo en el uso de tecnologías ?'),
            preserve_default=False,
        ),
    ]
